# Python CircleCI 2.0 configuration file
version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
        - image: circleci/python:3.6.9

    working_directory: ~/MERlin

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
            bash Miniconda3-latest-Linux-x86_64.sh -b -p $HOME/miniconda
            #touch ~/.bashrc
            #echo ".  $HOME/miniconda/etc/profile.d/conda.sh" >> ~/.bashrc
            #echo "conda activate" >> ~/.bashrc
            #source ~/.bashrc
            source ~/miniconda/bin/activate root
            conda activate base
            conda config --set always_yes true
            conda config --set quiet true
            conda create -n merlin_env python=3.6
            source activate merlin_env
            conda install rtree
            conda install pytables
            cd ~
            printf 'DATA_HOME=~\nANALYSIS_HOME=~\nPARAMETERS_HOME=~\n' >.merlinenv
            pip install -e MERlin
            cd ~/MERlin
      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            source ~/miniconda/bin/activate root
            conda activate base
            source activate merlin_env
            cd ~/MERlin/test
            mkdir ~/test-reports
            pytest -v --cov=~/test-reports/ --junitxml=~/test-reports/junit.xml

      - codecov/upload:
          file: ~/test-reports/.coverage

      - store_test_results:
          path: ~/test-reports

      - store_artifacts:
          path: ~/test-reports
